export WANDB_PROJECT=HYPER
python main_exorl.py fb  quadruped rnd  --eval_tasks stand jump roll roll_fast escape  --tilt_start_step 0 --z_mix_ratio 0.5   --tilt --tilt_ridge_min 1e-8 --tilt_candidate_multiplier 5 --tilt_refresh_interval 5 --tilt_init_geom_ratio 0.98 --tilt_temperature_start 0.5 --tilt_temperature_end 0.5 --tilt_ridge_alpha 1e-2 --tilt_beta 0.99 --tilt_linear --tilt_uniform_mix 0.5 --seed 42
python main_exorl.py td_jepa quadruped rnd  --eval_tasks stand jump roll roll_fast escape   --tilt_start_step 0  --tilt --tilt_ridge_min 1e-8  --tilt_candidate_multiplier 5 --tilt_refresh_interval 5 --tilt_init_geom_ratio 0.98 --tilt_temperature_start 0.5 --tilt_temperature_end 0.5 --tilt_ridge_alpha 1e-2 --tilt_beta 0.99 --tilt_linear --tilt_uniform_mix 0.5 --seed 42

python main_exorl.py fb quadruped rnd  --eval_tasks stand jump roll roll_fast escape  --tilt_start_step 0 --z_mix_ratio 0.5   --tilt --tilt_ridge_min 1e-8 --tilt_candidate_multiplier 5 --tilt_refresh_interval 5 --tilt_init_geom_ratio 0.98 --tilt_temperature_start 0.5 --tilt_temperature_end 0.5 --tilt_ridge_alpha 1e-2 --tilt_beta 0.99 --tilt_linear --tilt_uniform_mix 0.5 --seed 43
python main_exorl.py td_jepa quadruped rnd  --eval_tasks stand jump roll roll_fast escape   --tilt_start_step 0  --tilt --tilt_ridge_min 1e-8  --tilt_candidate_multiplier 5 --tilt_refresh_interval 5 --tilt_init_geom_ratio 0.98 --tilt_temperature_start 0.5 --tilt_temperature_end 0.5 --tilt_ridge_alpha 1e-2 --tilt_beta 0.99 --tilt_linear --tilt_uniform_mix 0.5 --seed 43

python main_exorl.py fb  quadruped rnd  --eval_tasks stand jump roll roll_fast escape  --tilt_start_step 0 --z_mix_ratio 0.5  --tilt --tilt_ridge_min 1e-8 --tilt_candidate_multiplier 5 --tilt_refresh_interval 5 --tilt_init_geom_ratio 0.98 --tilt_temperature_start 0.5 --tilt_temperature_end 0.5 --tilt_ridge_alpha 1e-2 --tilt_beta 0.99 --tilt_linear --tilt_uniform_mix 0.5 --seed 44
python main_exorl.py td_jepa quadruped rnd  --eval_tasks stand jump roll roll_fast escape   --tilt_start_step 0  --tilt --tilt_ridge_min 1e-8  --tilt_candidate_multiplier 5 --tilt_refresh_interval 5 --tilt_init_geom_ratio 0.98 --tilt_temperature_start 0.5 --tilt_temperature_end 0.5 --tilt_ridge_alpha 1e-2 --tilt_beta 0.99 --tilt_linear --tilt_uniform_mix 0.5 --seed 44

python main_exorl.py fb  quadruped rnd  --eval_tasks stand jump roll roll_fast escape  --tilt_start_step 0 --z_mix_ratio 0.5  --tilt --tilt_ridge_min 1e-8 --tilt_candidate_multiplier 5 --tilt_refresh_interval 5 --tilt_init_geom_ratio 0.98 --tilt_temperature_start 0.5 --tilt_temperature_end 0.5 --tilt_ridge_alpha 1e-2 --tilt_beta 0.99 --tilt_linear --tilt_uniform_mix 0.5 --seed 45
python main_exorl.py td_jepa quadruped rnd  --eval_tasks stand jump roll roll_fast escape   --tilt_start_step 0  --tilt --tilt_ridge_min 1e-8  --tilt_candidate_multiplier 5 --tilt_refresh_interval 5 --tilt_init_geom_ratio 0.98 --tilt_temperature_start 0.5 --tilt_temperature_end 0.5 --tilt_ridge_alpha 1e-2 --tilt_beta 0.99 --tilt_linear --tilt_uniform_mix 0.5 --seed 45
