export WANDB_PROJECT=HYPER
python main_exorl.py fb point_mass_maze rnd --eval_tasks reach_top_left reach_top_right reach_bottom_left reach_bottom_right --z_mix_ratio 0.5 --tilt --tilt_ridge_min 1e-8 --tilt_start_step 100 --tilt_candidate_multiplier 5 --tilt_refresh_interval 5 --tilt_init_geom_ratio 0.99 --tilt_temperature_start 1 --tilt_temperature_end 1 --tilt_ridge_alpha 1e-2   --seed 42  --tilt_beta 0.99   
python main_exorl.py fb point_mass_maze rnd --eval_tasks reach_top_left reach_top_right reach_bottom_left reach_bottom_right --z_mix_ratio 0.5 --tilt --tilt_ridge_min 1e-8 --tilt_start_step 100 --tilt_candidate_multiplier 5 --tilt_refresh_interval 5 --tilt_init_geom_ratio 0.99 --tilt_temperature_start 1 --tilt_temperature_end 1 --tilt_ridge_alpha 1e-2   --seed 43  --tilt_beta 0.99   
python main_exorl.py fb point_mass_maze rnd --eval_tasks reach_top_left reach_top_right reach_bottom_left reach_bottom_right --z_mix_ratio 0.5 --tilt --tilt_ridge_min 1e-8 --tilt_start_step 100 --tilt_candidate_multiplier 5 --tilt_refresh_interval 5 --tilt_init_geom_ratio 0.99 --tilt_temperature_start 1 --tilt_temperature_end 1 --tilt_ridge_alpha 1e-2   --seed 44  --tilt_beta 0.99   
python main_exorl.py fb point_mass_maze rnd --eval_tasks reach_top_left reach_top_right reach_bottom_left reach_bottom_right --z_mix_ratio 0.5 --tilt --tilt_ridge_min 1e-8 --tilt_start_step 100 --tilt_candidate_multiplier 5 --tilt_refresh_interval 5 --tilt_init_geom_ratio 0.99 --tilt_temperature_start 1 --tilt_temperature_end 1 --tilt_ridge_alpha 1e-2   --seed 45  --tilt_beta 0.99   

python main_exorl.py fb point_mass_maze rnd --eval_tasks reach_top_left reach_top_right reach_bottom_left reach_bottom_right --z_mix_ratio 0.5 --tilt --tilt_ridge_min 1e-8 --tilt_start_step 100 --tilt_candidate_multiplier 5 --tilt_refresh_interval 5 --tilt_init_geom_ratio 0.99 --tilt_temperature_start 1000 --tilt_temperature_end 1000 --tilt_ridge_alpha 1e-2   --seed 42  --tilt_beta 0.99   
python main_exorl.py fb point_mass_maze rnd --eval_tasks reach_top_left reach_top_right reach_bottom_left reach_bottom_right --z_mix_ratio 0.5 --tilt --tilt_ridge_min 1e-8 --tilt_start_step 100 --tilt_candidate_multiplier 5 --tilt_refresh_interval 5 --tilt_init_geom_ratio 0.99 --tilt_temperature_start 1000 --tilt_temperature_end 1000 --tilt_ridge_alpha 1e-2   --seed 43  --tilt_beta 0.99   
python main_exorl.py fb point_mass_maze rnd --eval_tasks reach_top_left reach_top_right reach_bottom_left reach_bottom_right --z_mix_ratio 0.5 --tilt --tilt_ridge_min 1e-8 --tilt_start_step 100 --tilt_candidate_multiplier 5 --tilt_refresh_interval 5 --tilt_init_geom_ratio 0.99 --tilt_temperature_start 1000 --tilt_temperature_end 1000 --tilt_ridge_alpha 1e-2   --seed 44  --tilt_beta 0.99   
python main_exorl.py fb point_mass_maze rnd --eval_tasks reach_top_left reach_top_right reach_bottom_left reach_bottom_right --z_mix_ratio 0.5 --tilt --tilt_ridge_min 1e-8 --tilt_start_step 100 --tilt_candidate_multiplier 5 --tilt_refresh_interval 5 --tilt_init_geom_ratio 0.99 --tilt_temperature_start 1000 --tilt_temperature_end 1000 --tilt_ridge_alpha 1e-2   --seed 45  --tilt_beta 0.99   
